// <auto-generated />
using System;
using DataLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(TpeduContext))]
    [Migration("20251107024412_Add_Attribute_In_Feedback_Entity")]
    partial class Add_Attribute_In_Feedback_Entity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LessonID");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("StudentID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Attendance_Lesson_Student");

                    b.HasIndex(new[] { "LessonId" }, "IX_Attendance_LessonID");

                    b.HasIndex(new[] { "StudentId" }, "IX_Attendance_StudentID");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.AvailabilityBlock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TutorID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TutorId" }, "IX_AvailabilityBlock_TutorID");

                    b.ToTable("AvailabilityBlock", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ClassStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStudentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OnlineStudyLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudentLimit")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Class__CB1927C08608731F");

                    b.HasIndex(new[] { "TutorId" }, "IX_Class_TutorId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ClassAssign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("ClassId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StudentId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassId" }, "IX_ClassAssign_ClassId");

                    b.HasIndex(new[] { "StudentId" }, "IX_ClassAssign_StudentId");

                    b.ToTable("ClassAssign", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("ClassStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OnlineStudyLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Subject")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ClassReq__33A8517A858CC078");

                    b.HasIndex(new[] { "StudentId" }, "IX_ClassRequest_StudentId");

                    b.HasIndex(new[] { "TutorId" }, "IX_ClassRequest_TutorId");

                    b.ToTable("ClassRequest", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequestSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassRequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassRequestId" }, "IX_ClassRequestSchedule_ClassRequestId");

                    b.ToTable("ClassRequestSchedule", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ClassSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ClassID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassId" }, "IX_ClassSchedule_ClassID");

                    b.ToTable("ClassSchedule", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Escrow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TutorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Escrow__Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Escrow", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Feedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPublicOnTutorProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("ToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__6A4BEDD6F1A4F2BB");

                    b.HasIndex("FromUserId", "ToUserId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Feedback_From_To_Lesson")
                        .HasFilter("[FromUserId] IS NOT NULL AND [ToUserId] IS NOT NULL AND [LessonId] IS NOT NULL");

                    b.HasIndex(new[] { "FromUserId" }, "IX_Feedback_FromUserId");

                    b.HasIndex(new[] { "LessonId" }, "IX_Feedback_LessonId");

                    b.HasIndex(new[] { "ToUserId" }, "IX_Feedback_ToUserId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.LearningMaterial", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Type")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Learning__C50610F7D00FA71A");

                    b.HasIndex(new[] { "ClassId" }, "IX_LearningMaterial_ClassId");

                    b.ToTable("LearningMaterial", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassId" }, "IX_Lesson_ClassId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Media", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TutorProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Media__B2C2B5CF88789472");

                    b.HasIndex(new[] { "LessonId" }, "IX_Media_LessonId");

                    b.HasIndex(new[] { "OwnerUserId" }, "IX_Media_OwnerUserId");

                    b.HasIndex(new[] { "TutorProfileId" }, "IX_Media_TutorProfileId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("DataLayer.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Message__C87C0C9C8E34634D");

                    b.HasIndex(new[] { "ReceiverId" }, "IX_Message_ReceiverId");

                    b.HasIndex(new[] { "SenderId" }, "IX_Message_SenderId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__20CF2E120CBDEB29");

                    b.HasIndex(new[] { "UserId" }, "IX_Notification_UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ParentProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedStudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__ParentPr__D339516FB6AE405F");

                    b.HasIndex(new[] { "LinkedStudentId" }, "IX_ParentProfile_LinkedStudentId");

                    b.HasIndex(new[] { "UserId" }, "IX_ParentProfile_UserId");

                    b.ToTable("ParentProfile", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReporterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TargetLessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Report__D5BD48055AA94599");

                    b.HasIndex(new[] { "ReporterId" }, "IX_Report_ReporterId");

                    b.HasIndex(new[] { "TargetLessonId" }, "IX_Report_TargetLessonId");

                    b.HasIndex(new[] { "TargetUserId" }, "IX_Report_TargetUserId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Role__8AFACE1A59C340B0");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ScheduleEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlockId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("BlockID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LessonId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LessonID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TutorID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TutorId", "StartTime", "EndTime")
                        .HasDatabaseName("IX_ScheduleEntry_Tutor_TimeRange");

                    b.HasIndex(new[] { "BlockId" }, "IX_ScheduleEntry_BlockID");

                    b.HasIndex(new[] { "LessonId" }, "IX_ScheduleEntry_LessonID");

                    b.HasIndex(new[] { "TutorId", "StartTime" }, "UQ_ScheduleEntry_Tutor_StartTime")
                        .IsUnique();

                    b.ToTable("ScheduleEntry", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.StudentProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreferredSubjects")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__32C52B9926DD24AA");

                    b.HasIndex(new[] { "UserId" }, "IX_StudentProfile_UserId");

                    b.ToTable("StudentProfile", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CounterpartyUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__55433A6B");

                    b.HasIndex(new[] { "WalletId" }, "IX_Transaction_WalletId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.TutorApplication", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ClassRequestId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationId")
                        .HasName("PK__TutorApp__C93A4C990407478F");

                    b.HasIndex("ClassRequestId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorApplication", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.TutorProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ApprovedByAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvideNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SpecialSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeachingExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("TeachingLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeachingSubjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__TutorPro__77C70FE2F53C4D03");

                    b.HasIndex(new[] { "UserId" }, "IX_TutorProfile_UserId");

                    b.ToTable("TutorProfile", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BannedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__User__1788CC4C79B935BF");

                    b.HasIndex(new[] { "RoleId" }, "IX_User_RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105343AB23C97")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL)");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFrozen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Wallet__84D4F90E");

                    b.HasIndex(new[] { "UserId" }, "UQ_Wallet_UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Wallet", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Lesson");

                    b.HasOne("DataLayer.Entities.StudentProfile", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_StudentProfile");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataLayer.Entities.AvailabilityBlock", b =>
                {
                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("AvailabilityBlocks")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AvailabilityBlock_TutorProfile");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.Class", b =>
                {
                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("Classes")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK__Class__TutorId__07C12930");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassAssign", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("ClassAssigns")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_ClassAssign_Class");

                    b.HasOne("DataLayer.Entities.StudentProfile", "Student")
                        .WithMany("ClassAssigns")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_ClassAssign_StudentProfile");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequest", b =>
                {
                    b.HasOne("DataLayer.Entities.StudentProfile", "Student")
                        .WithMany("ClassRequests")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__ClassRequ__Stude__0A9D95DB");

                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("ClassRequests")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK__ClassRequ__Tutor__0B91BA14");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequestSchedule", b =>
                {
                    b.HasOne("DataLayer.Entities.ClassRequest", "ClassRequest")
                        .WithMany("ClassRequestSchedules")
                        .HasForeignKey("ClassRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClassRequestSchedule_ClassRequest");

                    b.Navigation("ClassRequest");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassSchedule", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassSchedule_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DataLayer.Entities.Feedback", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "FromUser")
                        .WithMany("FeedbackFromUsers")
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("FK__Feedback__FromUs__1332DBDC");

                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("Feedbacks")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK__Feedback__Lesson__151B244E");

                    b.HasOne("DataLayer.Entities.User", "ToUser")
                        .WithMany("FeedbackToUsers")
                        .HasForeignKey("ToUserId")
                        .HasConstraintName("FK__Feedback__ToUser__14270015");

                    b.Navigation("FromUser");

                    b.Navigation("Lesson");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("DataLayer.Entities.LearningMaterial", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__LearningM__Class__123EB7A3");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DataLayer.Entities.Lesson", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Lesson_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DataLayer.Entities.Media", b =>
                {
                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("Media")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK__Media__LessonId__114A936A");

                    b.HasOne("DataLayer.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.TutorProfile", "TutorProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("TutorProfileId");

                    b.Navigation("Lesson");

                    b.Navigation("OwnerUser");

                    b.Navigation("TutorProfile");
                });

            modelBuilder.Entity("DataLayer.Entities.Message", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Message__Receive__19DFD96B");

                    b.HasOne("DataLayer.Entities.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Message__SenderI__18EBB532");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DataLayer.Entities.Notification", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__1AD3FDA4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.ParentProfile", b =>
                {
                    b.HasOne("DataLayer.Entities.StudentProfile", "LinkedStudent")
                        .WithMany("ParentProfiles")
                        .HasForeignKey("LinkedStudentId")
                        .HasConstraintName("FK__ParentPro__Linke__05D8E0BE");

                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("ParentProfiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ParentPro__UserI__04E4BC85");

                    b.Navigation("LinkedStudent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.Report", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "Reporter")
                        .WithMany("ReportReporters")
                        .HasForeignKey("ReporterId")
                        .HasConstraintName("FK__Report__Reporter__160F4887");

                    b.HasOne("DataLayer.Entities.Lesson", "TargetLesson")
                        .WithMany("Reports")
                        .HasForeignKey("TargetLessonId")
                        .HasConstraintName("FK__Report__TargetLe__17F790F9");

                    b.HasOne("DataLayer.Entities.User", "TargetUser")
                        .WithMany("ReportTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("FK__Report__TargetUs__17036CC0");

                    b.Navigation("Reporter");

                    b.Navigation("TargetLesson");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("DataLayer.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("DataLayer.Entities.AvailabilityBlock", "Block")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("BlockId")
                        .HasConstraintName("FK_ScheduleEntry_AvailabilityBlock");

                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK_ScheduleEntry_Lesson");

                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleEntry_TutorProfile");

                    b.Navigation("Block");

                    b.Navigation("Lesson");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.StudentProfile", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__StudentPr__UserI__02FC7413");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.Transaction", b =>
                {
                    b.HasOne("DataLayer.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .HasConstraintName("FK_Transaction_Wallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DataLayer.Entities.TutorApplication", b =>
                {
                    b.HasOne("DataLayer.Entities.ClassRequest", "ClassRequest")
                        .WithMany("TutorApplications")
                        .HasForeignKey("ClassRequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Application_Request");

                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("TutorApplications")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FK_Application_Tutor");

                    b.Navigation("ClassRequest");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.TutorProfile", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("TutorProfiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TutorProf__UserI__06CD04F7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.User", b =>
                {
                    b.HasOne("DataLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleId__02084FDA");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataLayer.Entities.Wallet", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Wallet_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.AvailabilityBlock", b =>
                {
                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.Class", b =>
                {
                    b.Navigation("ClassAssigns");

                    b.Navigation("ClassSchedules");

                    b.Navigation("LearningMaterials");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequest", b =>
                {
                    b.Navigation("ClassRequestSchedules");

                    b.Navigation("TutorApplications");
                });

            modelBuilder.Entity("DataLayer.Entities.Lesson", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Feedbacks");

                    b.Navigation("Media");

                    b.Navigation("Reports");

                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataLayer.Entities.StudentProfile", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ClassAssigns");

                    b.Navigation("ClassRequests");

                    b.Navigation("ParentProfiles");
                });

            modelBuilder.Entity("DataLayer.Entities.TutorProfile", b =>
                {
                    b.Navigation("AvailabilityBlocks");

                    b.Navigation("Certificates");

                    b.Navigation("ClassRequests");

                    b.Navigation("Classes");

                    b.Navigation("ScheduleEntries");

                    b.Navigation("TutorApplications");
                });

            modelBuilder.Entity("DataLayer.Entities.User", b =>
                {
                    b.Navigation("FeedbackFromUsers");

                    b.Navigation("FeedbackToUsers");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("Notifications");

                    b.Navigation("ParentProfiles");

                    b.Navigation("ReportReporters");

                    b.Navigation("ReportTargetUsers");

                    b.Navigation("StudentProfiles");

                    b.Navigation("TutorProfiles");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("DataLayer.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
